//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationTier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationTier.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2016 Nick Jorens and Tim Steenbeke - Humble programmers, teamed up for globalisation in .Net..
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new ticket.
        /// </summary>
        public static string CreateANewTicket {
            get {
                return ResourceManager.GetString("CreateANewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string dutch {
            get {
                return ResourceManager.GetString("dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give an answer to a ticket.
        /// </summary>
        public static string GiveAnAnswerToATicket {
            get {
                return ResourceManager.GetString("GiveAnAnswerToATicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === HELPDESK - SUPPORT CENTER ===.
        /// </summary>
        public static string HELPDESKSUPPORTCENTER {
            get {
                return ResourceManager.GetString("HELPDESKSUPPORTCENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a hardware problem (y/n)?.
        /// </summary>
        public static string IsItAHardwareProblem {
            get {
                return ResourceManager.GetString("IsItAHardwareProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose your language.
        /// </summary>
        public static string LanguageChoice {
            get {
                return ResourceManager.GetString("LanguageChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark ticket as &apos;closed&apos;.
        /// </summary>
        public static string MarkTicketAsClosed {
            get {
                return ResourceManager.GetString("MarkTicketAsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the unit.
        /// </summary>
        public static string NameOfTheUnit {
            get {
                return ResourceManager.GetString("NameOfTheUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No a valid choice!.
        /// </summary>
        public static string NoAValidChoice {
            get {
                return ResourceManager.GetString("NoAValidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question/Problem.
        /// </summary>
        public static string QuestionProblem {
            get {
                return ResourceManager.GetString("QuestionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Tickets.
        /// </summary>
        public static string ShowAllTickets {
            get {
                return ResourceManager.GetString("ShowAllTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show answers to a ticket.
        /// </summary>
        public static string ShowAnswersToATicket {
            get {
                return ResourceManager.GetString("ShowAnswersToATicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details of a ticket.
        /// </summary>
        public static string ShowDetailsOfATicket {
            get {
                return ResourceManager.GetString("ShowDetailsOfATicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error!.
        /// </summary>
        public static string ThereWasAnUnexpectedError {
            get {
                return ResourceManager.GetString("ThereWasAnUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number.
        /// </summary>
        public static string TicketNumber {
            get {
                return ResourceManager.GetString("TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketResponse not valid!.
        /// </summary>
        public static string TicketResponseNotValid {
            get {
                return ResourceManager.GetString("TicketResponseNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User number.
        /// </summary>
        public static string UserNumber {
            get {
                return ResourceManager.GetString("UserNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
